# Usar la imagen base de .NET SDK 8.0 para compilar y publicar la aplicación
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copiar los archivos del proyecto y restaurar las dependencias
COPY *.csproj ./
RUN dotnet restore

# Copiar el resto de los archivos y compilar la aplicación
COPY . ./
RUN dotnet publish -c Release -o out

# Usar la imagen base de .NET Runtime 8.0 para ejecutar la aplicación
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .

# Exponer el puerto 80 para el tráfico HTTP
EXPOSE 70

# Configurar el punto de entrada para ejecutar la aplicación
ENTRYPOINT ["dotnet", "MiAplicacionWeb.dll"]

